# ReadTheDocs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - cp -r examples docs/notebooks
      - python .claude/scripts/generate_cognitive_docs.py

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: docs/requirements-docs.txt
    - method: pip
      path: .
