# ReadTheDocs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      # Pre-convert notebooks to markdown (30x faster than mkdocs-jupyter)
      # This script converts .ipynb -> .md and updates mkdocs.yml accordingly
      - python .claude/scripts/prepare_notebooks_for_docs.py
      # Copy supporting files
      - cp examples/README.md docs/notebooks/ || true
      - cp examples/AGENTS.md docs/notebooks/ || true
      # Generate cognitive infrastructure docs
      - python .claude/scripts/generate_cognitive_docs.py

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: docs/requirements-docs.txt
    - method: pip
      path: .
