"""Curated notebook contracts survive regeneration and agree across surfaces."""

import importlib.util
from pathlib import Path
import re

import pytest


ROOT = Path(__file__).resolve().parents[1]


def load_script(name):
    spec = importlib.util.spec_from_file_location(name, ROOT / ".claude/scripts" / f"{name}.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


generator = load_script("generate_examples_index")
metadata_generator = load_script("generate_notebooks_metadata")
validator = load_script("validate_notebooks_yml")


def test_curated_contracts_survive_metadata_refresh():
    metadata = generator.load_yml_meta(ROOT)
    assert metadata
    for name, entry in metadata.items():
        refreshed = metadata_generator.build_entry(ROOT / "examples" / entry["filename"], entry, {})
        for field in generator.FUNCTIONAL_FIELDS:
            assert (field in refreshed) == (field in entry), (name, field)
            if field in entry:
                assert refreshed[field] == entry[field], (name, field)


def test_human_and_json_catalog_share_curated_contracts():
    metadata = generator.load_yml_meta(ROOT)
    groups, count = generator.build_gallery(ROOT / "examples", ROOT, copy_thumbnails=False)
    records = {item["id"]: item for group in groups for item in group["notebooks"]}
    markdown, human_count, _ = generator.build_index_markdown(ROOT / "examples")
    assert human_count == count == len(records)
    assert count == len([entry for entry in metadata.values() if not entry.get("excluded")])
    for name, record in records.items():
        entry = metadata[name]
        assert entry["summary"].strip()
        assert entry["tags"]
        assert generator._table_text(entry["summary"]) in markdown
        for field in generator.FUNCTIONAL_FIELDS:
            assert (field in record) == (field in entry), (name, field)
            if field not in entry:
                continue
            assert record[field] == entry[field]
            values = entry[field] if isinstance(entry[field], list) else [entry[field]]
            assert all(generator._table_text(value) in markdown for value in values)
    assert "does not mean outputs are absent" in markdown
    assert "not a support badge" in markdown


@pytest.mark.parametrize("entry", [
    {},
    {"input_families": ["1D result HDF"]},
    {"evidence_scope": "Retained-result inspection only"},
])
def test_optional_contract_fields_allow_omission(entry):
    assert validator.validate_functional_fields(entry) == []


@pytest.mark.parametrize("entry", [
    {"input_families": "1D result HDF"},
    {"outputs": []},
    {"operations": ["read", None]},
    {"runtime_requirements": [""]},
    {"evidence_scope": None},
    {"evidence_scope": "   "},
])
def test_optional_contract_fields_reject_ambiguous_values(entry):
    assert validator.validate_functional_fields(entry)


def test_capability_map_routes_to_existing_sources():
    page = ROOT / "docs/capabilities.md"
    text = page.read_text(encoding="utf-8")
    for target in re.findall(r"\]\(([^)]+)\)", text):
        path = target.split("#", 1)[0]
        if path.startswith("notebooks/"):
            source = ROOT / "examples" / Path(path).with_suffix(".ipynb").name
            assert source.is_file(), target
        elif path == "examples/index.json":
            continue  # Generated by the catalog build; may not exist in a clean checkout.
        else:
            assert (page.parent / path).is_file(), target
    assert "experimental" in text
    assert not re.search(r"\]\([^)]*notebooks/(223|311)_", text)


def test_function_inventory_distinguishes_code_from_prose_and_constants():
    notebook = {"cells": [{"cell_type": "code", "source": '''
# HdfMesh.get_mesh_perimeter("01")
print("RasProcess.exe and RasUsgsCore.get_discharge are prose")
names = {"ras.exe", "rasmapper.exe"}
limit = GeomCrossSection.MAX_XS_POINTS
GeomCrossSection.MAX_XS_POINTS()
directory = RasExamples.projects_dir
operations = {"function": RasMapperLayerCommandWorkflow.run_command}
callback = RasPlan.get_plan_path
RasPlan.update_plan_intervals("01", computation_interval="5MIN")
print(f"{RasPlan.get_shortid('01')}")
ras.project_path
HdfMesh.missing_reader("01")
'''}]}
    diagnostics = []
    assert metadata_generator.derive_functions(notebook, diagnostics) == [
        "GeomCrossSection.MAX_XS_POINTS", "HdfMesh.missing_reader",
        "RasMapperLayerCommandWorkflow.run_command",
        "RasPlan.get_plan_path", "RasPlan.get_shortid", "RasPlan.update_plan_intervals",
        "ras.project_path",
    ]
    assert diagnostics == []


def test_ipython_syntax_does_not_hide_python_calls():
    pytest.importorskip("IPython")
    notebook = {"cells": [{"cell_type": "code", "source": [
        "%matplotlib inline\n", "RasCmdr.compute_plan('01')\n"
    ]}]}
    diagnostics = []
    assert metadata_generator.derive_functions(notebook, diagnostics) == ["RasCmdr.compute_plan"]
    assert diagnostics == []


def test_unparseable_cell_keeps_candidates_with_explicit_warning():
    notebook = {"cells": [{"cell_type": "code", "source": [
        "if (:\n", "    HdfMesh.missing_reader('01')\n"
    ]}]}
    diagnostics = []
    assert metadata_generator.derive_functions(notebook, diagnostics) == ["HdfMesh.missing_reader"]
    assert len(diagnostics) == 1
    assert "cell 0" in diagnostics[0] and "regex fallback" in diagnostics[0]


def test_manifest_exports_resolve_without_accepting_arbitrary_members():
    from ras_commander.api_surface import PUBLIC_MODULES

    assert {"ras_commander.geom", "ras_commander.hdf", "ras_commander.gui",
            "ras_commander.terrain"} <= set(PUBLIC_MODULES)
    index = validator.build_symbol_index()
    for symbol in ["GeomHtab.get_optimization_report", "HdfStruc1D.get_structure_max_values",
                   "RasMapperBankLineWorkflow.create_bank_lines_from_xs_bank_stations",
                   "RasTerrainMod.get_terrain_profile", "ras.project_path"]:
        assert validator.classify_symbol(symbol, *index) == "ok", symbol
    assert validator.classify_symbol("HdfMesh.missing_reader", *index) == "bad"
    assert validator.classify_symbol("GeomCrossSection.MAX_XS_POINTS", *index) == "bad"


def test_unavailable_approved_module_remains_explicit(monkeypatch):
    original_import = validator.importlib.import_module

    def import_without_gui(name):
        if name == "ras_commander.gui":
            raise ImportError("optional desktop dependency unavailable")
        return original_import(name)

    monkeypatch.setattr(validator.importlib, "import_module", import_without_gui)
    diagnostics = []
    index = validator.build_symbol_index(diagnostics)
    assert validator.classify_symbol(
        "RasMapperBankLineWorkflow.create_bank_lines_from_xs_bank_stations", *index
    ) == "unverifiable"
    assert any("ras_commander.gui unavailable" in message for message in diagnostics)


def test_rashydrocompare_public_export_preserves_identity():
    import ras_commander
    from ras_commander.RasHydroCompare import RasHydroCompare

    assert "RasHydroCompare" in ras_commander.__all__
    assert ras_commander.RasHydroCompare is RasHydroCompare
    assert validator.classify_symbol("RasHydroCompare.compare_hydrographs",
                                     *validator.build_symbol_index()) == "ok"
