name: Publish Python Package (Windows)

on:
  push:
    tags:
      - 'v*'  # Triggers when pushing a new version tag, e.g., v0.1.1

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout the latest version of the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Install dependencies (twine, wheel, setuptools)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel twine setuptools

    # Build the distribution files
    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    # Publish to PyPI
    - name: Publish package to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}  # Ensure this secret is set in your GitHub repository
      run: |
        twine upload dist/*
